version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: kintaraa-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=kintaraa
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 